### ISSUE TITLE
Repository does not have a release file’

### ISSUE THREAD

**Issue by Lsw-98** [geworfener/using_pyseal#1]
When I run build-docker.sh, it reports the following error. What should I do?
![1622185336(1)](https://user-images.githubusercontent.com/70066311/119943644-e5374800-bfc5-11eb-85d3-c80a9472ad59.jpg)

**Comment by geworfener** [comment]
Hi @Lsw-98, Ubuntu 17.10 is not supported any more... I upgraded to 18.04 via upstream and it's working again now!
