### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rkarn** [geworfener/using_pyseal#3]
I tried to open jupyter notebook container. I get following error:

root@ip-172-31-26-203:~/using_pyseal# sh run-docker-jupyter.sh 
run-docker-jupyter.sh: 5: run-docker-jupyter.sh: Bad substitution
run-docker-jupyter.sh: 5: run-docker-jupyter.sh: pushd: not found
f17c14ed77b9753bd23829e32d2b880d0afae22b2a6bf45ab2aa818f1fc869c4
run-docker-jupyter.sh: 14: run-docker-jupyter.sh: popd: not found
   
Also, runing "run-docker.sh"  created container but it exits out. No result is shown.

**Comment by geworfener** [comment]
Hi,

jupyter notebooks come from upstream only, I have not used them.

`run-docker.sh` should print the test results from `using_pyseal/test_homenc.py`.
